---
- name: task_24_2
  hosts: lab-junos
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get facts
      junos_facts:

    - name: Print version
      debug:
        var: ansible_facts.net_interfaces
