---
- name: Get arp
  hosts: lab-junos
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  
  tasks:
    - name: Get arp
      junos_command:
        commands:
          - show arp
          - show int ters
      register: result

    - name: Print result
      debug:
        var: result.stdout_lines
