---
- name: task_24_2
  hosts: lab-junos
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieving information from devices running Junos OS
      juniper_get_facts:
        host: "{{ inventory_hostname }}"

    - name: Print version
      debug:
        var: junos.version
